#!/bin/bash -e
# -e = errexit - will exit after first command with non-zero return code

# Install the pre-commit hook in a top-level repo by making a symbolic link:
#   ln -sf ../../scripts/pre-commit .git/hooks/pre-commit

make lock
