name: pyblhost CI

on: [push, pull_request]

jobs:
  dist:
    name: Build dist
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5

    - name: Setup uv
      uses: astral-sh/setup-uv@v6

    - name: Build dist
      run: make build

    - name: Upload dist as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.sha }}
        path: dist
        retention-days: 1
        if-no-files-found: error

  checks:
    name: Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5

    - name: Setup uv
      uses: astral-sh/setup-uv@v6

    - name: Check code with ruff and mypy
      run: make -j static-checks

  release:
    needs: [dist, checks]
    name: Release
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v6

    - uses: actions/download-artifact@v5
      with:
        path: dist
        name: dist-${{ github.sha }}

    - name: Check dist
      id: twine
      run: uvx twine check dist/*

    - name: Publish to PyPI
      id: pypi
      if: ${{ ! cancelled() && steps.twine.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
      run: |
        uvx twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist/*

    - name: Calculate checksums
      run: |
        pushd dist
          sha256sum * > SHA256SUMS
        popd
        cat dist/SHA256SUMS

    - name: Publish to Github Release
      if: ${{ ! cancelled() && steps.pypi.conclusion == 'success' }}
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        draft: true
        fail_on_unmatched_files: true
